/* eslint-disable linebreak-style */

export const Frontend = [
  'React',
  'Next.js',
  'Vue.js',
  'Nuxt.js',
  'Angular',
  'Svelte',
  'SvelteKit',
  'Remix',
  'Astro',
  'TypeScript',
  'JavaScript',
  'Tailwind CSS',
  'Bootstrap',
  'Material UI',
  'Chakra UI',
  'Ant Design',
  'Shadcn/ui',
  'Redux',
  'Zustand',
  'TanStack Query',
  'Framer Motion',
  'GSAP',
  'Vite',
  'Webpack',
];

export const Backend = [
  'Node.js',
  'Express.js',
  'NestJS',
  'Python',
  'Django',
  'FastAPI',
  'Flask',
  'Java',
  'Spring Boot',
  'Kotlin',
  'Go',
  'Gin',
  '.NET',
  'ASP.NET Core',
  'C#',
  'Ruby',
  'Ruby on Rails',
  'PHP',
  'Laravel',
  'Symfony',
];

export const APIs = [
  'REST APIs',
  'GraphQL',
  'gRPC',
  'tRPC',
  'Apollo Server',
  'Socket.io',
  'OpenAPI / Swagger',
  'WebSockets',
];

export const Databases = [
  'PostgreSQL',
  'MySQL',
  'MariaDB',
  'SQL Server',
  'Oracle',
  'MongoDB',
  'Redis',
  'Elasticsearch',
  'DynamoDB',
  'Firestore',
  'Supabase',
  'PlanetScale',
  'CockroachDB',
  'Cassandra',
  'Neo4j',
  'InfluxDB',
  'SQLite',
  'Prisma',
  'TypeORM',
  'Sequelize',
  'Django ORM',
  'Hibernate',
];

export const Mobile = [
  'React Native',
  'Flutter',
  'Swift',
  'SwiftUI',
  'Kotlin',
  'Jetpack Compose',
  'Expo',
  'Ionic',
  '.NET MAUI',
  'Xamarin',
  'Objective-C',
];

export const Cloud = [
  'AWS',
  'Microsoft Azure',
  'Google Cloud',
  'Cloudflare',
  'Vercel',
  'Netlify',
  'DigitalOcean',
  'Heroku',
  'Firebase',
  'AWS Amplify',
];

export const DevOps = [
  'Docker',
  'Kubernetes',
  'Terraform',
  'Ansible',
  'GitHub Actions',
  'GitLab CI',
  'CircleCI',
  'Jenkins',
  'Datadog',
  'Grafana',
  'CloudWatch',
  'Prometheus',
  'ArgoCD',
  'Helm',
];

export const Design = [
  'Figma',
  'Figma AI',
  'Sketch',
  'Adobe XD',
  'Adobe CC',
  'Framer',
  'Canva',
  'InVision',
  'Principle',
  'Zeplin',
  'Miro',
];

export const AI = [
  'OpenAI',
  'Anthropic',
  'Google Gemini',
  'LangChain',
  'LlamaIndex',
  'Hugging Face',
  'Pinecone',
  'pgvector',
  'Vapi',
  'ElevenLabs',
  'Twilio',
  'Ollama',
];

export const PaymentsAuth = [
  'Stripe',
  'Razorpay',
  'PayPal',
  'Auth0',
  'Clerk',
  'Okta',
  'Firebase Auth',
  'Keycloak',
  'Passport.js',
];

export const SecuritySEO = [
  'Burp Suite',
  'OWASP ZAP',
  'Lighthouse',
  'Ahrefs',
  'Google Search Console',
  'Semrush',
  'Snyk',
  'SonarQube',
];

export const ServiceStacks = {
  webDevelopment: [
    ...Frontend,
    ...Backend,
    ...APIs,
    ...Databases,
    ...Cloud,
  ],
  mobileDevelopment: [
    ...Mobile,
    ...Backend.slice(0, 8),
    'Firebase',
    'REST APIs',
    'GraphQL',
    'PostgreSQL',
    'MongoDB',
    'Redis',
    'AWS',
    'Azure',
  ],
  uiUxDesign: Design,
  aiGenai: AI,
  saasCrm: [
    ...Frontend.slice(0, 12),
    ...Backend.slice(0, 10),
    ...APIs.slice(0, 5),
    ...Databases.slice(0, 10),
    ...PaymentsAuth,
    ...Cloud.slice(0, 6),
  ],
  cloudDevops: [
    ...Cloud,
    ...DevOps,
    'PostgreSQL',
    'MySQL',
    'MongoDB',
    'Redis',
    'Elasticsearch',
  ],
  securitySeo: SecuritySEO,
};

export const PartnerCategories = [
  { title: 'Cloud & Hosting', items: Cloud },
  { title: 'Frontend & UI', items: Frontend },
  { title: 'Backend Frameworks', items: Backend },
  { title: 'APIs & Integration', items: APIs },
  { title: 'Databases & ORMs', items: Databases },
  { title: 'Mobile', items: Mobile },
  { title: 'AI & GenAI', items: AI },
  { title: 'Payments & Auth', items: PaymentsAuth },
  { title: 'DevOps & Monitoring', items: DevOps },
  { title: 'Design', items: Design },
];
